### PR TITLE
update zh-Hant.lrpoj (deleted old part translation)

### PR DESCRIPTION
**Pull request by powenn**
@PwnedC99 
Excuse me  sir,is the third table view controller scene (object iD: I5H-bE-iec) still needed ?

### CODE REVIEW

**Comment by 0xfffffff0075e2040** [comment]
What do you mean?

**Comment by powenn** [comment]
> What do you mean?

Please wait a minute, I am sending picture to your Twitter 😉

**Comment by powenn** [comment]
@RPwnage these are modified things:
deleted old part Chinese traditional translation 
add arabic localization but not support RTL,could you tag it like unperfectly pls

**Comment by 0xfffffff0075e2040** [comment]
Should I merge now? Is this version correct?

**Comment by powenn** [comment]
> Should I merge now? Is this version correct?

Yes please, I have told him that he can upload the better version to replace it

**Pull request closed without merging**
